numpy and pandas 

In [1]:
l=[6,7,8,9,10,15,98]

In [2]:
l[-1:]

[98]

In [3]:
l[2:]

[8, 9, 10, 15, 98]

In [4]:
l[:2]

[6, 7]

In [5]:
l[:]

[6, 7, 8, 9, 10, 15, 98]

In [6]:
l[:-1]

[6, 7, 8, 9, 10, 15]

In [7]:
import numpy as np

In [8]:
a=np.array([6,7,8,9])
a

array([6, 7, 8, 9])

In [9]:
a[0:2]

array([6, 7])

In [10]:
a[-1]

9

In [11]:
b=np.array([[6,7,8],[1,2,3],[7,8,9]])
b

array([[6, 7, 8],
       [1, 2, 3],
       [7, 8, 9]])

In [12]:
b[0:]

array([[6, 7, 8],
       [1, 2, 3],
       [7, 8, 9]])

In [13]:
b[1]

array([1, 2, 3])

In [14]:
b[:,-1]

array([8, 3, 9])

In [15]:
b[1:,2]

array([3, 9])

In [16]:
b[2,:]

array([7, 8, 9])

In [17]:
b[:,1:3]

array([[7, 8],
       [2, 3],
       [8, 9]])

In [18]:
b[:1]

array([[6, 7, 8]])

In [19]:
b[1:]

array([[1, 2, 3],
       [7, 8, 9]])

In [20]:
b[1:]

array([[1, 2, 3],
       [7, 8, 9]])

In [21]:
b[1:-1]

array([[1, 2, 3]])

In [22]:
b

array([[6, 7, 8],
       [1, 2, 3],
       [7, 8, 9]])

In [23]:
b[2,0:2]

array([7, 8])

In [24]:
b[2,0:]

array([7, 8, 9])

In [25]:
b[1,2]

3

In [26]:
b[0:2]

array([[6, 7, 8],
       [1, 2, 3]])

In [27]:
b[0]

array([6, 7, 8])

In [28]:
b[0:-1]

array([[6, 7, 8],
       [1, 2, 3]])

In [29]:
b[0:2,2]

array([8, 3])

In [30]:
b

array([[6, 7, 8],
       [1, 2, 3],
       [7, 8, 9]])

In [31]:
a =np.array([[6,7,8],[1,2,3],[7,8,9]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [7, 8, 9]])

In [32]:
for i in a.flat:
    print(i,end=',')

6,7,8,1,2,3,7,8,9,

In [33]:
a=np.arange(6).reshape(3,2)

In [34]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [35]:
b= np.arange(6,12).reshape(3,2)

In [36]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [37]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [38]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [39]:
a= np.arange(40).reshape(5,8)

In [40]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [41]:
40/8

5.0

In [42]:
np.hsplit(a,2)

[array([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19],
        [24, 25, 26, 27],
        [32, 33, 34, 35]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31],
        [36, 37, 38, 39]])]

In [43]:
v= np.vsplit(a,5)

In [44]:
v

[array([[0, 1, 2, 3, 4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29, 30, 31]]),
 array([[32, 33, 34, 35, 36, 37, 38, 39]])]

In [45]:
for i in v:
    print(i)

[[0 1 2 3 4 5 6 7]]
[[ 8  9 10 11 12 13 14 15]]
[[16 17 18 19 20 21 22 23]]
[[24 25 26 27 28 29 30 31]]
[[32 33 34 35 36 37 38 39]]


In [46]:
6*4

24

In [47]:
a= np.arange(24).reshape(4,6)

In [48]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [49]:
b=a>15

In [50]:
b

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [51]:
a[b]

array([16, 17, 18, 19, 20, 21, 22, 23])

In [52]:
a[b]=-1

In [53]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, -1, -1],
       [-1, -1, -1, -1, -1, -1]])

In [54]:
b

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [55]:
a= np.arange(12).reshape(3,4)

In [56]:
for x in np.nditer(a):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [57]:
a=np.ones((2,3))

In [58]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [59]:
b= np.full((3,3),2)

In [60]:
b

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [61]:
np.matmul(a,b)

array([[6., 6., 6.],
       [6., 6., 6.]])

In [62]:
a= np.array([[3,5],[-1,1]])

In [63]:
a

array([[ 3,  5],
       [-1,  1]])

In [64]:
b=np.array([[-2,2,3],[3,5,-2]])
b

array([[-2,  2,  3],
       [ 3,  5, -2]])

In [65]:
d=np.matmul(a,b)
d

array([[ 9, 31, -1],
       [ 5,  3, -5]])

In [66]:
c=np.identity(3)

In [67]:
np.linalg.det(c)

1.0

In [68]:
np.sum(a)

8

In [69]:
np.sum(b)

9

In [70]:
np.min(a)

-1

In [71]:
np.max(b)

5

In [72]:
np.max(d,axis=1)
# 0 for row 
# 1 for columns

array([31,  5])

In [73]:
d 

array([[ 9, 31, -1],
       [ 5,  3, -5]])

Pandas

In [74]:
import pandas as pd

In [75]:
x=['a','b','c','d','e']
y=[1,2,3,4,5]
a=pd.Series(x,y)

In [76]:
a

1    a
2    b
3    c
4    d
5    e
dtype: object

In [77]:
type(a)

pandas.core.series.Series

In [78]:
df= pd.DataFrame(a)

In [79]:
df

0
1  a
2  b
3  c
4  d
5  e

In [80]:
r= np.random.randint(1,25,(5,4))

In [81]:
r

array([[ 5, 10, 16, 16],
       [22,  1, 23, 19],
       [11, 21,  8,  8],
       [ 3, 18, 12, 12],
       [20, 21, 17,  7]])

In [82]:
df= pd.DataFrame(r)

In [83]:
df

0   1   2   3
0   5  10  16  16
1  22   1  23  19
2  11  21   8   8
3   3  18  12  12
4  20  21  17   7

In [84]:
df= pd.DataFrame(r,['a','b','c','d','e'],['w','x','y','z'])

In [85]:
df

w   x   y   z
a   5  10  16  16
b  22   1  23  19
c  11  21   8   8
d   3  18  12  12
e  20  21  17   7

In [86]:
df['s']=df['y']+df['z']

In [87]:
df

w   x   y   z   s
a   5  10  16  16  32
b  22   1  23  19  42
c  11  21   8   8  16
d   3  18  12  12  24
e  20  21  17   7  24

In [88]:
df.drop('e',axis=0,inplace=True)

In [89]:
# df.drop('s',axis=1,inplace=True)

In [90]:
df

w   x   y   z   s
a   5  10  16  16  32
b  22   1  23  19  42
c  11  21   8   8  16
d   3  18  12  12  24

Indexing and Slicing in matrix/DataFrame

In [91]:
df

w   x   y   z   s
a   5  10  16  16  32
b  22   1  23  19  42
c  11  21   8   8  16
d   3  18  12  12  24

In [92]:
df.loc['c','y']

8

In [93]:
df.loc['c':]

w   x   y   z   s
c  11  21   8   8  16
d   3  18  12  12  24

In [94]:
df.loc[:,'x':]

x   y   z   s
a  10  16  16  32
b   1  23  19  42
c  21   8   8  16
d  18  12  12  24

In [95]:
df.loc['c':'d','y':'s']

y   z   s
c   8   8  16
d  12  12  24

In [96]:
df.loc[:,'y':'s']

y   z   s
a  16  16  32
b  23  19  42
c   8   8  16
d  12  12  24

In [97]:
df.loc['a':'b','x':'y']

x   y
a  10  16
b   1  23

In [98]:
df.iloc[0:2,1:3]

x   y
a  10  16
b   1  23

In [99]:
d= pd.DataFrame({'a':[1,2,3,4,5], 'b':[6,8,9,10,np.nan], 'c':[11,12,4,np.nan,np.nan], 'd':[2,5,np.nan,np.nan,np.nan], 'e':[3,np.nan,np.nan,np.nan,np.nan]})

In [100]:
d

a     b     c    d    e
0  1   6.0  11.0  2.0  3.0
1  2   8.0  12.0  5.0  NaN
2  3   9.0   4.0  NaN  NaN
3  4  10.0   NaN  NaN  NaN
4  5   NaN   NaN  NaN  NaN

In [101]:
d.dropna()

a    b     c    d    e
0  1  6.0  11.0  2.0  3.0

In [102]:
d.dropna(thresh=3)

a    b     c    d    e
0  1  6.0  11.0  2.0  3.0
1  2  8.0  12.0  5.0  NaN
2  3  9.0   4.0  NaN  NaN

In [103]:
d.fillna(1)

a     b     c    d    e
0  1   6.0  11.0  2.0  3.0
1  2   8.0  12.0  5.0  1.0
2  3   9.0   4.0  1.0  1.0
3  4  10.0   1.0  1.0  1.0
4  5   1.0   1.0  1.0  1.0

In [104]:
d['b'].fillna(d['b'].mean(),inplace=True)

In [105]:
d

a      b     c    d    e
0  1   6.00  11.0  2.0  3.0
1  2   8.00  12.0  5.0  NaN
2  3   9.00   4.0  NaN  NaN
3  4  10.00   NaN  NaN  NaN
4  5   8.25   NaN  NaN  NaN

In [106]:
d['c'].fillna(d['c'].mean(),inplace=True)

In [107]:
d

a      b     c    d    e
0  1   6.00  11.0  2.0  3.0
1  2   8.00  12.0  5.0  NaN
2  3   9.00   4.0  NaN  NaN
3  4  10.00   9.0  NaN  NaN
4  5   8.25   9.0  NaN  NaN