In [1]:
c=np.zeros((5,5))

<IPython.core.display.Javascript object>

In [2]:
# c[0:3]=7
c

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [3]:
c[0:-1]

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
c[0]=1

In [5]:
c[-1]=1

In [6]:
c[:,0]=1

In [7]:
c[:,-1]=1

In [8]:
c[2,2]=7

In [9]:
c

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 7., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])