Numpy

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
a.ndim

1

In [4]:
a.shape

(3,)

In [5]:
a.dtype

dtype('int32')

In [6]:
b = np.array([[2,3,4,5],[4,5,3,6]],'int16')
print(b)

[[2 3 4 5]
 [4 5 3 6]]


In [7]:
b.itemsize

2

In [8]:
b.size

8

In [9]:
b.dtype

dtype('int16')

 Access/change specific rows and columns  [row,column], startindex:endindex


In [10]:
A= np.array([[1,2,3,4,5,6,7],[9,8,7,6,5,4,3]])
A

array([[1, 2, 3, 4, 5, 6, 7],
       [9, 8, 7, 6, 5, 4, 3]])

In [11]:
A[0,1]

2

In [12]:
A.shape

(2, 7)

In [13]:
A[0,1:-1:2]

array([2, 4, 6])

In [14]:
A[0:-1]

array([[1, 2, 3, 4, 5, 6, 7]])

In [15]:
A[:,2]

array([3, 7])

In [16]:
A[:,0]

array([1, 9])

In [17]:
A[0,2:4]

array([3, 4])

In [18]:
A[1,5:8]

array([4, 3])

In [19]:
A

array([[1, 2, 3, 4, 5, 6, 7],
       [9, 8, 7, 6, 5, 4, 3]])

In [20]:
A[0:2,3:6]

array([[4, 5, 6],
       [6, 5, 4]])

In [21]:
A

array([[1, 2, 3, 4, 5, 6, 7],
       [9, 8, 7, 6, 5, 4, 3]])

initializing different types of array

In [22]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [23]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [25]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.full((3,3,2), 109)

array([[[109, 109],
        [109, 109],
        [109, 109]],

       [[109, 109],
        [109, 109],
        [109, 109]],

       [[109, 109],
        [109, 109],
        [109, 109]]])

In [27]:
c = np.full_like(a,60)

In [28]:
print(c)

[60 60 60]


In [29]:
c.shape

(3,)

In [30]:
c = np.full_like(A,6)
print(c)

[[6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6]]


In [31]:
c.shape

(2, 7)

In [32]:
c.reshape(7,2)

array([[6, 6],
       [6, 6],
       [6, 6],
       [6, 6],
       [6, 6],
       [6, 6],
       [6, 6]])

In [33]:
np.random.rand(4,9)

array([[0.26696821, 0.67154639, 0.60086402, 0.32656434, 0.22959641,
        0.87722324, 0.81467645, 0.56412622, 0.58848032],
       [0.70144677, 0.45359679, 0.53612311, 0.63603688, 0.6228813 ,
        0.01565034, 0.55404632, 0.71747661, 0.04417414],
       [0.83657634, 0.542329  , 0.70513124, 0.37419325, 0.98804672,
        0.18756261, 0.48646409, 0.2620291 , 0.50012697],
       [0.57327831, 0.65827543, 0.58647781, 0.02863231, 0.29984051,
        0.90766466, 0.68066597, 0.07353399, 0.42903388]])

In [34]:
np.random.random_sample()

0.22932304656504054

In [35]:

np.random.randint(8,18,size=(4,9))

array([[12, 16,  9, 11, 14,  8,  8, 10, 14],
       [15, 11, 10, 14, 11, 12, 17, 17,  9],
       [11, 10, 13,  9, 14, 16, 11, 16, 17],
       [10, 13, 12,  8, 12, 17, 16, 17, 11]])

In [36]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
arr= np.array([[1,2,3]])
arr1=np.repeat(arr,3,axis=0)

In [39]:
arr1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [40]:
arr

array([[1, 2, 3]])

In [41]:
a=np.array([1,2,3])
b=a.copy()
a

array([1, 2, 3])

In [42]:
b

array([1, 2, 3])

In [43]:
b[0]=900

In [44]:
a/2

array([0.5, 1. , 1.5])

In [45]:
np.cos(A)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
         0.96017029,  0.75390225],
       [-0.91113026, -0.14550003,  0.75390225,  0.96017029,  0.28366219,
        -0.65364362, -0.9899925 ]])

In [46]:
np.sin(A)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
        -0.2794155 ,  0.6569866 ],
       [ 0.41211849,  0.98935825,  0.6569866 , -0.2794155 , -0.95892427,
        -0.7568025 ,  0.14112001]])

In [47]:
np.tan(A)

array([[ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
        -0.29100619,  0.87144798],
       [-0.45231566, -6.79971146,  0.87144798, -0.29100619, -3.38051501,
         1.15782128, -0.14254654]])